### ISSUE TITLE
Need to depend on time >= 1.5

### ISSUE THREAD

**Issue by thomasdziedzic** [dmjio/ses-html#1]
Otherwise I get the following error:

```
Configuring ses-html-0.2.1.2...
Building ses-html-0.2.1.2...
Preprocessing library ses-html-0.2.1.2...
[1 of 1] Compiling Network.SES      ( src/Network/SES.hs, dist/dist-sandbox-3471194a/build/Network/SES.o )

src/Network/SES.hs:31:62:
    Module ‘Data.Time.Format’ does not export ‘defaultTimeLocale’
```

Seems like `defaultTimeLocale` was introduced with time 1.5

**Comment by thomasdziedzic** [comment]
As a consequence, I think this also bumps the base requirement to 4.8 and ghc to 7.10.

Note this only applies to ses-html 0.2.1.2

**Comment by dmjio** [comment]
@thomasdziedzic yea, time should be >= 1.5, my bad. I'll fix that, but why do you think the base requirement should now be >=4.8?

**Comment by thomasdziedzic** [comment]
@dmjio ah nvm, base shouldn't need that constraint. I forgot that even though ghc 7.10 ships with time 1.5, it doesn't mean that the package has to use the time package shipped with ghc.

**Comment by dmjio** [comment]
`0.3.0.0` is on hackage, let me know if you have issues and we'll reopen.

**Comment by thomasdziedzic** [comment]
thanks!
